<?php
/* @var Jayanka\HelloWorld\Block\Hello $block */
$User = $block->getAllUsers();
?>

<form method="post" action="<?= $block->getAddUserPostUrl() ?>">
   <fieldset>
       <div>
            <label for="manufacturer"><?= __("Manufacturer") ?></label>
           <input type="text" name="name" id="name" />
      </div>
       <div>
            <!-- <label for="model"><?= __("Model") ?>
           <input type="text" name="model" id="model" /> -->
       </div>
      <input type="submit" value="<?= __("Add Car") ?>" />
   </fieldset>
</form>
<hr />
<?php if (count($users) > 0): ?>
 <table border="1">
      <tr>
         <th><?= __("post_id") ?></th>
          <th><?= __("name") ?>
            <?= __("created_at") ?></th>
        </tr>
       <?php foreach ($Users as $user): ?>
            <tr>
               <td><?= $user->getPost_id() ?>
               <td><?= $user->getName() ?>
              <td><?= $user->getCreated_at() ?>
           </tr>
      <?php endforeach; ?>
    </table>
<?php else: ?>
    <h1><?= __("You have no cars yet :(") ?></h1>
<?php endif; ?>