# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [@ASPCA, @gamestop, @NASA, @MIA]
patreon: # Replace with a single Patreon brother Dave welman
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi https://www.crazylabs.com/pps
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name Tor.onion., cloud-foundry
liberapay: # Replace with a single Liberapay @ULTA
issuehunt: # Replace with a single IssueHunt @WE
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://g.page/testing35/', 'https://boardkings.onelink.me/Fymc/1dc741ab']
